/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Apuraçao;
import Controller.C_Pdf;
import Controller.C_Selic;
import Model.Apuraçao;
import Model.Modelo_tabelas.Model_table_resultado_apuraçao;
import Model.Selic;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.DefaultListModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Victony
 */
public class J_Gerenciar_selic extends javax.swing.JFrame {
    
    J_Visualizar_selic j_atualizar_selic;
    ArrayList<ArrayList<String>> matriz_tratada;
    DefaultListModel modelo_anos = new DefaultListModel();
    
    public J_Gerenciar_selic(J_Visualizar_selic J_atualizar_selic) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        j_atualizar_selic = J_atualizar_selic;
        Link.setText("<html><u>http://idg.receita.fazenda.gov.br/orientacao/tributaria/pagamentos-e-parcelamentos/taxa-de-juros-selic</u></html>");
        Label_Erro.setText(" ");
        List_Anos.setModel(modelo_anos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Incidencia = new javax.swing.JPanel();
        B_Remover_tudo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Label_Erro = new javax.swing.JLabel();
        B_Retornar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Link = new javax.swing.JLabel();
        Painel_Busca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text_Tabela_selic = new javax.swing.JTextArea();
        B_Inserir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        B_Limpar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_Anos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Incidencia.setBackground(new java.awt.Color(204, 204, 204));
        Painel_Incidencia.setPreferredSize(new java.awt.Dimension(900, 160));

        B_Remover_tudo.setBackground(new java.awt.Color(153, 153, 153));
        B_Remover_tudo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        B_Remover_tudo.setForeground(new java.awt.Color(0, 0, 0));
        B_Remover_tudo.setText("Remover Todas as Tabelas do Banco");
        B_Remover_tudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Remover_tudoActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gerenciador Selic");

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        Label_Erro.setBackground(new java.awt.Color(153, 153, 153));
        Label_Erro.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        Label_Erro.setForeground(new java.awt.Color(153, 0, 0));
        Label_Erro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Erro.setText("Erro");

        B_Retornar.setBackground(new java.awt.Color(102, 102, 102));
        B_Retornar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        B_Retornar.setForeground(new java.awt.Color(0, 0, 0));
        B_Retornar.setText("Retornar");
        B_Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RetornarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione completamente a tabela de juros selic que deseja atualizar/adicionar os percentuais necessários, apenas uma tabela por vez.");

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Link das tabelas Selic >>");

        Link.setForeground(new java.awt.Color(0, 153, 255));
        Link.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Link.setText("http://idg.receita.fazenda.gov.br/orientacao/tributaria/pagamentos-e-parcelamentos/taxa-de-juros-selic");
        Link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Painel_IncidenciaLayout = new javax.swing.GroupLayout(Painel_Incidencia);
        Painel_Incidencia.setLayout(Painel_IncidenciaLayout);
        Painel_IncidenciaLayout.setHorizontalGroup(
            Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(Painel_IncidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_IncidenciaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Retornar))
                    .addGroup(Painel_IncidenciaLayout.createSequentialGroup()
                        .addGroup(Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(Painel_IncidenciaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Link)))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_IncidenciaLayout.createSequentialGroup()
                        .addComponent(Label_Erro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_Remover_tudo)))
                .addContainerGap())
        );
        Painel_IncidenciaLayout.setVerticalGroup(
            Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_IncidenciaLayout.createSequentialGroup()
                .addGroup(Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(B_Retornar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Link))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_IncidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_Remover_tudo)
                    .addComponent(Label_Erro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Painel_Incidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 140));

        Painel_Busca.setBackground(new java.awt.Color(204, 204, 204));
        Painel_Busca.setPreferredSize(new java.awt.Dimension(900, 340));

        Text_Tabela_selic.setBackground(new java.awt.Color(204, 204, 204));
        Text_Tabela_selic.setColumns(20);
        Text_Tabela_selic.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 10)); // NOI18N
        Text_Tabela_selic.setForeground(new java.awt.Color(0, 0, 0));
        Text_Tabela_selic.setRows(5);
        jScrollPane1.setViewportView(Text_Tabela_selic);

        B_Inserir.setBackground(new java.awt.Color(153, 153, 153));
        B_Inserir.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        B_Inserir.setForeground(new java.awt.Color(0, 0, 0));
        B_Inserir.setText("Inserir Tabela Selic");
        B_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_InserirActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Insira a tabela de juros Selic no campo a baixo");

        jSeparator6.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));

        B_Limpar.setBackground(new java.awt.Color(153, 153, 153));
        B_Limpar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        B_Limpar.setForeground(new java.awt.Color(0, 0, 0));
        B_Limpar.setText("Limpar Texto");
        B_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LimparActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Anos Atualizados");

        List_Anos.setBackground(new java.awt.Color(204, 204, 204));
        List_Anos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        List_Anos.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(List_Anos);

        javax.swing.GroupLayout Painel_BuscaLayout = new javax.swing.GroupLayout(Painel_Busca);
        Painel_Busca.setLayout(Painel_BuscaLayout);
        Painel_BuscaLayout.setHorizontalGroup(
            Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(Painel_BuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_BuscaLayout.createSequentialGroup()
                        .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_BuscaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 370, Short.MAX_VALUE))
                            .addGroup(Painel_BuscaLayout.createSequentialGroup()
                                .addComponent(B_Limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_Inserir)))
                        .addGap(18, 18, 18))
                    .addGroup(Painel_BuscaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Painel_BuscaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel13))
                .addContainerGap())
        );
        Painel_BuscaLayout.setVerticalGroup(
            Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_BuscaLayout.createSequentialGroup()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_BuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Limpar)
                    .addComponent(B_Inserir))
                .addContainerGap())
        );

        getContentPane().add(Painel_Busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_Remover_tudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Remover_tudoActionPerformed
        C_Selic.Excluir_tudo();
        Label_Erro.setText("Todas as tabelas Selic foram excluidas");
    }//GEN-LAST:event_B_Remover_tudoActionPerformed

    private void B_RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RetornarActionPerformed
        j_atualizar_selic.Atualizar();
        j_atualizar_selic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_RetornarActionPerformed

    private void B_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_InserirActionPerformed
        ArrayList<ArrayList<String>> matriz_selic = new ArrayList<ArrayList<String>>();
        ArrayList<String> linha_selic = new ArrayList<String>();
        matriz_tratada = null;
        
        String selic = Text_Tabela_selic.getText();

        selic = selic.replaceAll("\\t", "|");
        selic = selic.replaceAll("\\n", "||");
        selic = selic.replaceAll(" ", "");
        selic = selic.replaceAll("%", "");
        selic = selic.replaceAll(",", ".");
        selic += "\n";
        
        char[] vetor = new char[selic.length()];
        selic.getChars(0, selic.length(), vetor, 0);
        String cedula = new String();
        int quant_linhas = 0, quant_registros = 0;
        
//Organização da matriz para tratamento        
        for(int i =0; i<vetor.length; i++){
            if(vetor[i] == '|' && i+1<vetor.length){
                if(vetor[i+1] == '|' && cedula.length()>0){
                    linha_selic.add(cedula);
                    if(matriz_selic.size()>0)
                        if(linha_selic.size() == matriz_selic.get(0).size()-1){
                            linha_selic.add(" ");
                        }
                        else if(linha_selic.size() <= matriz_selic.get(0).size()-1){
                            Label_Erro.setText("Tabela inserida invalida");
                            break;
                        }
                  
                    matriz_selic.add(linha_selic);
                    quant_registros += linha_selic.size();
                    linha_selic = new ArrayList<String>();
                    quant_linhas++;
                }
//condiçao final tabela incompleta
                else if(quant_linhas == 12 && linha_selic.size() == 7 && vetor[i+1] == '\n'){
                    linha_selic.add(cedula);
                    linha_selic.add(" ");
                    matriz_selic.add(linha_selic);
                    quant_registros += linha_selic.size();
                    linha_selic = new ArrayList<String>();
                    quant_linhas++; 
                }
                else if(cedula.length()>0){
                    linha_selic.add(cedula);
                }
                cedula = new String();
            }

            else if(vetor[i] == '\n'){
//condiçao final tabela completa
                if(quant_linhas == 12 && linha_selic.size() == 8){
                    linha_selic.add(cedula);
                    matriz_selic.add(linha_selic);
                    quant_registros += linha_selic.size();
                    linha_selic = new ArrayList<String>();
                    quant_linhas++;                   
                }                
            }
            else{
                cedula += vetor[i];
            }
            
        }
        
        
        if(quant_registros ==0 || quant_linhas == 0)
            Label_Erro.setText("Campo vazio");
        else
        if(quant_registros == 117 && quant_linhas == 13){
            C_Selic c_selic = new C_Selic();
            ArrayList<ArrayList<String>> matriz_futura = c_selic.Tratar_matriz_selic(matriz_tratada, matriz_selic);
            if(matriz_tratada != matriz_futura){
                matriz_tratada = matriz_futura;
                Label_Erro.setText("Tabela Inserida com Sucesso");
            }           
            else{
//Tabela ja Inserida
                Label_Erro.setText("Tabela já Inserida");
            }
        }
        else{
           Label_Erro.setText("Tabela informada de forma incorreta");
        }
        
        Text_Tabela_selic.setText("");
        
        modelo_anos.removeAllElements();
        if(matriz_tratada!=null)
            for(String ano: matriz_tratada.get(0)){
                modelo_anos.addElement(ano);
            }
         
        ArrayList<ArrayList<String>> aux_matriz_selic = new ArrayList<ArrayList<String>>();
//Invertendo matriz tratada        
        for(int i = 0; i < matriz_tratada.get(0).size(); i++){
            ArrayList<String> linha_tratada_selic = new ArrayList<String>();
            for(int c = 0; c < matriz_tratada.size(); c++){
                linha_tratada_selic.add(matriz_tratada.get(c).get(i));
            }
            aux_matriz_selic.add(linha_tratada_selic);
        }
        
        matriz_tratada = aux_matriz_selic;

        C_Selic.Realizar_atualizaçao(matriz_tratada);
        
    }//GEN-LAST:event_B_InserirActionPerformed

    private void LinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://idg.receita.fazenda.gov.br/orientacao/tributaria/pagamentos-e-parcelamentos/taxa-de-juros-selic"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(J_Gerenciar_selic.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(J_Gerenciar_selic.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LinkMouseClicked

    private void B_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LimparActionPerformed
        Text_Tabela_selic.setText("");
    }//GEN-LAST:event_B_LimparActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Inserir;
    private javax.swing.JButton B_Limpar;
    private javax.swing.JButton B_Remover_tudo;
    private javax.swing.JButton B_Retornar;
    private javax.swing.JLabel Label_Erro;
    private javax.swing.JLabel Link;
    private javax.swing.JList<String> List_Anos;
    private javax.swing.JPanel Painel_Busca;
    private javax.swing.JPanel Painel_Incidencia;
    private javax.swing.JTextArea Text_Tabela_selic;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
